### ISSUE TITLE
Fix functions vs S3/S4 methods

### ISSUE THREAD

**Issue by ArdiaD** [keblu/MSGARCH#2]
Check with Brian best way to prceed

**Comment by braverock** [comment]
Can you give me a little more context?  Are we looking for method/dispatch compatibility?

**Comment by ArdiaD** [comment]
Keven will send you an email by tomorrow with details

**Comment by keblu** [comment]
We currently have a function f.spec which take a vector of string of model like c("sGARCH_norm_sym","sGARCH_norm_sym"), and 2 boolean : do.mix, and do.shape.ind which indicate what type of specification we want (i.e., Mixture of GARCH and regime independent distribution). The f.spec takes these arguments and build a specification which is for now a list of class MSGARCH.SPEC containing all functions and variables related to the specification (see doc and f.spec.R which the last version has been uploaded today). This is in a way a factory pattern. We were wondering if it is worth having S3 or S4 methods and how to do it in this kind of factory pattern framework. I have limited knowledge concerning R object which is why I have done it this way at first.

**Comment by keblu** [comment]
I have switch everything to S3 method. This has resulted in 3 class MSGARCH_SPEC, MSGARCH_MLE_FIT, and MSGARCH_BAY_FIT that each has relevant methods that are documented in the new documentation. I have added another class for MSGARCH_SIM for summary and print for simulation (I might use xts or zoo package) . I still have to implement relevant summary and print for these classes.

**Comment by ArdiaD** [comment]
kev made a proposal which makes sense with S3
