### ISSUE TITLE
help("MSGARCH")

### ISSUE THREAD

**Issue by ArdiaD** [keblu/MSGARCH#23]
This should display the help of MSGARCH

**Comment by keblu** [comment]
help(package ="MSGARCH") will display the main help page/documentation while help("MSGARCH") will display the main MSGARCH page but only if the package is loaded (as if it is the documentation for the function MSGARCH and not the package) . I don't think this is an issue since this is the behavior observed for all package.

**Comment by ArdiaD** [comment]
This is not working with the latest version of the package

**Comment by ArdiaD** [comment]
fixed in the latest version
