### ISSUE TITLE
Prediction/ Forcasting

### ISSUE THREAD

**Issue by abon318** [keblu/MSGARCH#44]
Is it possible that you give a clear distinction between the function predict() and PredPdf().
What are each function predicting exactly in mathematical terms and maybe you can provide some example. I had a look at some presentations you gave regarding the package and also at the paper you publish but still it is all very confusing. 

Thank you in advance

**Comment by keblu** [comment]
Predict() will give you forecasts of the conditional volatility and give you, if the option is inputted, the simulation used for the forecasts from which you can obtain a predictive density forecast estimate. 

PredPdf() will not give you conditional volatility forecast but can be used to evaluate a vector of values on in sample predictive distributions (one for each date) or on forecasted predictive distributions obtain by simulation. This is set up with the do.its boolean. That way you can have a whole view of the predictive distributions or get likelihood score for each values in the vector.

You would have to do some additional work if you want to evaluate a vector of values on the simulation result from predict() which is why PredPdf() exist. Plus, predict does not do in sample evaluation.

**Comment by keblu** [comment]
Also, some of the online presentation are a bit dated, please look at the vignette at : https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2845809

**Comment by abon318** [comment]
Thank-you very much for the prompt reply. So you have a particular mathematical method which you follow for the  conditional volatility forecasts? As on the vignette I notice only how the forecasting the shape of the distribution is done.
