### ISSUE TITLE
loading objects generates pointer error

### ISSUE THREAD

**Issue by onnokleen** [keblu/MSGARCH#48]
Hello,

after we talked about your package at Brussel SoFiE summer school, I wanted to try out your package for an empirical application in a paper with my supervisor. Thanks a lot for me not having to implement all that stuff on my own :) 👍 

However, there is a weird error when I try to use your generic functions on MSGARCH-objects after reloading them from disk:

```r
library(MSGARCH)

# create model specification
spec <- CreateSpec()

# load data
data("SMI", package = "MSGARCH")

# fit the model on the data by ML
fit <- FitML(spec = spec, data = SMI)
summary(fit)

# predict works
predict(fit)

save(fit, file = "fit.RData")
rm(fit)

# reload from disc

load("fit.RData")

# test whether generic functions work

fit

# however, error message says
# Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x0>,  : 
#  NULL value passed as symbol address

# or

predict(fit)

# generates the same error
```

Do you have an idea what may be the cause? I am happy to help if I can!

Best,

Onno

**Comment by keblu** [comment]
Hey !

The issue is known and related to the C++ object created when a specification is generated. The RData will save the R data but will not recreate the specification, which is a C++ object, when loaded. This means that all the C++ functionality related to the created specification are not there when you load the files, the function linked to a bad pointer (as the c++ object is not there anymore). This generate the 
# Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x0>,  : 
#  NULL value passed as symbol address

Usually, we check for that kind of error and recreate the specification according to the  original specfication in fit$spec to allow for save and load of results. Obviously there is an problem there and we need to fix it. 

In the mean time, you could recreate your specification and replace the fit$spec by the recreated specification.

```
library(MSGARCH)

# create model specification
spec <- CreateSpec()

# load data
data("SMI", package = "MSGARCH")

# fit the model on the data by ML
fit <- FitML(spec = spec, data = SMI)
summary(fit)

# predict works
predict(fit)

save(fit, file = "fit.RData")
rm(fit)

# reload from disc

load("fit.RData")
#recreate spec
fit$spec = CreateSpec()

# test whether generic functions work
fit

predict(fit)

```

**Comment by onnokleen** [comment]
Thanks a lot - solves the problem :) 👍
