### ISSUE TITLE
Same codes produce very different results on 32-bit and 64 bit R on Windows

### ISSUE THREAD

**Issue by jinlin82** [keblu/MSGARCH#53]
Thanks for this great package.

However, same codes( fitting 3 regime models)  produce very different results on 32-bit and 64 bit R, for example:
``` r
spec=CreateSpec(variance.spec = list(model=c("sGARCH","sGARCH","sGARCH")),
                distribution.spec = list(distribution=c("sged","std","sged")))

### load data
data("SMI", package = "MSGARCH")

### fit the model on the data by ML
fit <- FitML(spec = spec, data = SMI)
summary(fit)
```

the results are very different on on 32-bit and 64 bit R.

I also try FitMCMC function, the results are different too but are close on 32-bit and 64 bit R.
The problem is FitMCMC's results are very different with FitML's results.

My R version is 3.5.1 on Windows 7.

after some google,  some r functions results may be different  but are close, see links
https://stat.ethz.ch/pipermail/r-devel/2011-February/059885.html
https://stackoverflow.com/questions/27258084/rstudio-and-r-terminal-give-different-outputs

**Comment by braverock** [comment]
I notice that you do not set a random seed in your example.

The process of choosing a seed is very different in 32 bit R vs. 64 bit R.  

In normal usage, I recommend recording the seed, rather than setting one.  For the purposes of reproducibility though, setting the same seed across computers is the only way to get the same results.

Small difference between 32 and 64 bit systems will persist due to floating point differences, of course.

If you do not set a seed, random simulation processes should converge to *similar* answers, given enough time, but they will never be the same.

**Comment by jinlin82** [comment]
Thanks for the reply.
I set the seed before the codes using(is this the right way?)：
``` r
library(MSGARCH)

set.seed(1234)

spec=CreateSpec(variance.spec = list(model=c("sGARCH","sGARCH","sGARCH")),
distribution.spec = list(distribution=c("sged","std","sged")))

### load data
data("SMI", package = "MSGARCH")

### fit the model on the data by ML
fit <- FitML(spec = spec, data = SMI)
summary(fit)
```

But still on 32-bit R， i get (just partial estimates, others omitted)
alpha0_3      0.7173
alpha1_3      0.2709
beta_3         0.7289

on 64-bit R， i get 
alpha0_3   0.9433 
alpha1_3   0.4168
beta_3     0.5723 

I think the difference is quite big.
Maybe you can reproduce the results using the above codes.

**Comment by keblu** [comment]
Your model is quite complex which will make the optimization process quite sensitive to floating point precision. This due to the fact that when estimating with FitML(), the optimization process compute a numerical approximations of derivatives of the parameters. 

If you take a simpler model:

        require(MSGARCH)
        set.seed(1234)
        data("SMI", package = "MSGARCH")
        spec=CreateSpec(variance.spec = list(model=c("sGARCH")),
                distribution.spec = list(distribution=c("sged")))
        fit <- FitML(spec = spec, data = SMI)
        summary(fit)

on 32 bit I get:

      alpha0_1   0.0510     0.0135  3.7735 8.050e-05
      alpha1_1   0.1176     0.0477  2.4658 6.835e-03
      beta_1     0.8415     0.0136 61.9368    <1e-16
      nu_1       1.4036     0.0495 28.3709    <1e-16
      xi_1       0.8476     0.0190 44.5401    <1e-16

on 64 bit I get:

      alpha0_1   0.0510     0.0135  3.7735 8.050e-05
      alpha1_1   0.1176     0.0477  2.4658 6.835e-03
      beta_1     0.8415     0.0136 61.9368    <1e-16
      nu_1       1.4036     0.0495 28.3709    <1e-16
      xi_1       0.8476     0.0190 44.5401    <1e-16

Which is basically the same. Moreover, looking at the parameter estimate for both 32 and 64 bits, the persistence in the third state is very low, so it is probably catching some "outliers":

              t+1|k=1 t+1|k=2 t+1|k=3
      t|k=1  0.8844  0.0000  0.1156
      t|k=2  0.0002  0.9959  0.0040
      t|k=3  0.9676  0.0317  0.0007

**Comment by jinlin82** [comment]
I see. I just choose "SMI" data as an example. For the data "SMI", maybe 2 regime model is better. But for my own data,  I want a 3 regime model and the AIC, BIC is lower for 3 regime model. 

I discovered the difference when I run the same code file on two Windows 7 computers one has 32-bit R and the other has 64-bit R.  I got very different results of parameters estimation. 

Actually， I have three very different kinds of estimation： 

1.    FitML -32 bit result
2.    FitML -64 bit result
3.    FitMCMC result (32-bit result and 64-bit result are close)

I just don't know which one should I choose as the best result.

**Comment by keblu** [comment]
Depends on your problem, but I would always go with 64 bits. If it's for risk measure estimation and the parameters are not super important, I think FitML() on a  32 and 64 bits platform is going to yield very similar results (and if you look at the AIC or BIC between the 32 and 64 bits estimation they are very very similar anyway).

If you want maximum likelihood estimation you have to go with FitML(). If you want Bayesian estimation (longer to estimate, but takes into consideration parameter uncertainty) you have to go with FitMCMC(). They are conceptually not necessary the same.

For FitMCMC(), the parameters are very similar between 32 and 64 bits because there is no need to get the numerical derivatives (we do however compute the starting parameters of the Markov chain using partially FitML(), so there might be a small difference even with set.seed() between 32 and 64 bits). 

If you use FitMCMC(), you need to be careful however regarding the length of the burn and the length of the chain to ensure that the start of the Markov chain is stable (such that your draw are from the posterior distribution). The default nburn and nmcmc are not necessary the most optimal for your estimation.

**Comment by jinlin82** [comment]
Thanks for the detailed reply. I will stick to 64-bit R.
