### ISSUE TITLE
Errors while trying to fit a model with FitML

### ISSUE THREAD

**Issue by mashvl** [keblu/MSGARCH#54]
I'm using MSGARCH to get volatility forecasts.

When I fit the model with FitML it produces an `Error: $ operator is invalid for atomic vectors` for some ranges of my data (ex. for the range [(6850):(6850+100)] it works fine but if fit the model for [(6850+40):(6850+40+100)] there errors arise), but this leads to forecasting, for example on rolling window, being impossible, since changing the starting value only leads to errors starting from different points. I use transformed log returns*100 data. 
Moreover, when I tried to change FitML to FitMCMC the resulted forecast values resulted to be extremely large (i.e 5e+37, 1.34e+124, etc) which is quite unrealistic.

The model I'm trying to fit is the following:
    

    MSmodel<-CreateSpec(variance.spec = list(model = c("sGARCH", "tGARCH", "eGARCH")),
                        distribution.spec = list(distribution = c("snorm", "std", "sged")),
                        switch.spec = list(do.mix = FALSE))
    MSmodel_est<-FitML(spec = MSmodel, data=window(FileAllData$ReturnsMS, start=6850+40, 
    end=6850+100+40))

The code for forecasting:
    

    windowLength = 100
    foreLength<-365
    MSforecasts <- vector(length=foreLength)
    for (d in 1:foreLength) {
      ###Obtain the rolling window 
      RollingWindow = FileAllData$ReturnsMS[(6850+d):(6850+windowLength+d)]
      MSmodel<-CreateSpec(variance.spec = list(model = c("sGARCH", "gjrGARCH", "eGARCH")),
                          distribution.spec = list(distribution = c("snorm", "std", "sged")),
                          switch.spec = list(do.mix = FALSE))
      MSmodel_est<-FitML(spec = MSmodel, data=RollingWindow) 
      ###Forecasting
      MSforecast<-predict(MSmodel_est, nahead = 1)
      MSforecasts[d]<-MSforecast$vol
    }
    MSforecasts

I saw quite the similar question has already been asked some time ago, but it is not very clear to me whether the problem has been solved and what can be done in my case.

**Comment by keblu** [comment]
Hi, this happens when one step in the estimation fails (either the starting parameter scheme or the final estimation). In your case, the estimation fails because the sample is way too small. 

This paper:
https://www.tandfonline.com/doi/abs/10.1080/13518470500039436

recommends at least 500 data point for a simple GARCH model (not even MSGARCH which is more complicated). 

In our paper:
https://www.sciencedirect.com/science/article/pii/S0169207018300840

we use 1,500 data points for a maximum of two states. 

In your case, even if there is no estimation failure, a sample of 100 will not give you a good estimation. Moreover, the rolling window scheme is often used to account for parameters change in the model, which is what MSGARCH is made for. So there is no real need to use a very small rolling window. Additionally, I would not expect the data to be in three different states in 100 days.

**Comment by mashvl** [comment]
Thanks a lot for such a quick reply! I've expanded the window to the length of 3000 and now everything is working fine.
