### ISSUE TITLE
in sample VaR

### ISSUE THREAD

**Issue by ArdiaD** [keblu/MSGARCH#8]
We need to improve the speed; slow especially when MCMC are used

**Comment by keblu** [comment]
The only solution I see is direct implementation of VaR and ES in C++ instead of the now sub-optimal implementation in R (the current implementation does alot of recalculation for nothing since it was a quick and dirty implementation before the end of the GSOC project). Still the current implementation works well for MLE, but is too long for Bayesian (which is proportional to the size of the chain).

**Comment by keblu** [comment]
A lot faster now. For large series and large MCMC chain though there is no miracle.
